---
- name: Install the ssh server package
  package:
    name: openssh-server
    state: present
  tags:
    - sshd

- name: Configure the ssh server
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    backup: yes
  tags:
    - sshd
  notify:
    - Restart the ssh daemon

- name: Enable and start the sshd service
  service:
    name: sshd
    state: started
    enabled: yes
  tags:
    - sshd
